// Code generated by db2go. DO NOT EDIT.
// https://github.com/civet148/db2go

package test

import "github.com/civet148/sqlca/v3"

const TableNameInventoryOut = "`inventory_out`" //出库主表 

const (
INVENTORY_OUT_COLUMN_ID = "id"
INVENTORY_OUT_COLUMN_CREATE_ID = "create_id"
INVENTORY_OUT_COLUMN_CREATE_NAME = "create_name"
INVENTORY_OUT_COLUMN_CREATE_TIME = "create_time"
INVENTORY_OUT_COLUMN_UPDATE_ID = "update_id"
INVENTORY_OUT_COLUMN_UPDATE_NAME = "update_name"
INVENTORY_OUT_COLUMN_UPDATE_TIME = "update_time"
INVENTORY_OUT_COLUMN_IS_DELETED = "is_deleted"
INVENTORY_OUT_COLUMN_DELETE_TIME = "delete_time"
INVENTORY_OUT_COLUMN_PRODUCT_ID = "product_id"
INVENTORY_OUT_COLUMN_ORDER_NO = "order_no"
INVENTORY_OUT_COLUMN_USER_ID = "user_id"
INVENTORY_OUT_COLUMN_USER_NAME = "user_name"
INVENTORY_OUT_COLUMN_QUANTITY = "quantity"
INVENTORY_OUT_COLUMN_WEIGHT = "weight"
INVENTORY_OUT_COLUMN_REMARK = "remark"
)

type InventoryOut--PACKAGE struct { 
	Id uint64 `json:"id,omitempty" db:"id" ` //主键ID 
	CreateId uint64 `json:"create_id,omitempty" db:"create_id" ` //创建人ID 
	CreateName string `json:"create_name,omitempty" db:"create_name" ` //创建人姓名 
	CreateTime string `json:"create_time,omitempty" db:"create_time" ` //创建时间 
	UpdateId uint64 `json:"update_id,omitempty" db:"update_id" ` //更新人ID 
	UpdateName string `json:"update_name,omitempty" db:"update_name" ` //更新人姓名 
	UpdateTime string `json:"update_time,omitempty" db:"update_time" ` //更新时间 
	IsDeleted int8 `json:"is_deleted,omitempty" db:"is_deleted" ` //删除状态(0: 未删除 1: 已删除) 
	DeleteTime string `json:"delete_time,omitempty" db:"delete_time" sqlca:"isnull"` //删除时间 
	ProductId uint64 `json:"product_id,omitempty" db:"product_id" ` //产品ID 
	OrderNo string `json:"order_no,omitempty" db:"order_no" ` //出库单号 
	UserId uint64 `json:"user_id,omitempty" db:"user_id" ` //收货人ID 
	UserName string `json:"user_name,omitempty" db:"user_name" ` //收货人姓名 
	Quantity sqlca.Decimal `json:"quantity,omitempty" db:"quantity" ` //数量 
	Weight sqlca.Decimal `json:"weight,omitempty" db:"weight" ` //净重 
	Remark string `json:"remark,omitempty" db:"remark" ` //备注 
}

func (do *InventoryOut--PACKAGE) GetId() uint64 { return do.Id } 
func (do *InventoryOut--PACKAGE) SetId(v uint64) { do.Id = v } 
func (do *InventoryOut--PACKAGE) GetCreateId() uint64 { return do.CreateId } 
func (do *InventoryOut--PACKAGE) SetCreateId(v uint64) { do.CreateId = v } 
func (do *InventoryOut--PACKAGE) GetCreateName() string { return do.CreateName } 
func (do *InventoryOut--PACKAGE) SetCreateName(v string) { do.CreateName = v } 
func (do *InventoryOut--PACKAGE) GetCreateTime() string { return do.CreateTime } 
func (do *InventoryOut--PACKAGE) SetCreateTime(v string) { do.CreateTime = v } 
func (do *InventoryOut--PACKAGE) GetUpdateId() uint64 { return do.UpdateId } 
func (do *InventoryOut--PACKAGE) SetUpdateId(v uint64) { do.UpdateId = v } 
func (do *InventoryOut--PACKAGE) GetUpdateName() string { return do.UpdateName } 
func (do *InventoryOut--PACKAGE) SetUpdateName(v string) { do.UpdateName = v } 
func (do *InventoryOut--PACKAGE) GetUpdateTime() string { return do.UpdateTime } 
func (do *InventoryOut--PACKAGE) SetUpdateTime(v string) { do.UpdateTime = v } 
func (do *InventoryOut--PACKAGE) GetIsDeleted() int8 { return do.IsDeleted } 
func (do *InventoryOut--PACKAGE) SetIsDeleted(v int8) { do.IsDeleted = v } 
func (do *InventoryOut--PACKAGE) GetDeleteTime() string { return do.DeleteTime } 
func (do *InventoryOut--PACKAGE) SetDeleteTime(v string) { do.DeleteTime = v } 
func (do *InventoryOut--PACKAGE) GetProductId() uint64 { return do.ProductId } 
func (do *InventoryOut--PACKAGE) SetProductId(v uint64) { do.ProductId = v } 
func (do *InventoryOut--PACKAGE) GetOrderNo() string { return do.OrderNo } 
func (do *InventoryOut--PACKAGE) SetOrderNo(v string) { do.OrderNo = v } 
func (do *InventoryOut--PACKAGE) GetUserId() uint64 { return do.UserId } 
func (do *InventoryOut--PACKAGE) SetUserId(v uint64) { do.UserId = v } 
func (do *InventoryOut--PACKAGE) GetUserName() string { return do.UserName } 
func (do *InventoryOut--PACKAGE) SetUserName(v string) { do.UserName = v } 
func (do *InventoryOut--PACKAGE) GetQuantity() sqlca.Decimal { return do.Quantity } 
func (do *InventoryOut--PACKAGE) SetQuantity(v sqlca.Decimal) { do.Quantity = v } 
func (do *InventoryOut--PACKAGE) GetWeight() sqlca.Decimal { return do.Weight } 
func (do *InventoryOut--PACKAGE) SetWeight(v sqlca.Decimal) { do.Weight = v } 
func (do *InventoryOut--PACKAGE) GetRemark() string { return do.Remark } 
func (do *InventoryOut--PACKAGE) SetRemark(v string) { do.Remark = v } 
